### PR TITLE
button link for actor website

### PR DESCRIPTION
**Pull request by rthai6**

### CODE REVIEW

**Review by nicharesuk — APPROVED** [review]
Looks great!

**Comment by swindiggie** [comment]
Can you put `as="a"` as a prop for Button? It prevents the focus from being on the button after the user moves the mouse away. An example is in ButtonRow.js

**Review by swindiggie — CHANGES_REQUESTED** [review]
Put `as="a"` as a prop to Button

**Comment by rthai6** [comment]
Added the as="a"

**Review by swindiggie — APPROVED** [review]

**Pull request merged**
