### PR TITLE
fix overflow bug

### PR DESCRIPTION
**Pull request by rthai6**

### CODE REVIEW

**Comment by swindiggie** [comment]
What was overflowing?

**Comment by rthai6** [comment]
At least for me, if a name was too large and overflowed, then sometimes it would make the info side of the modal larger than usual

**Comment by rthai6** [comment]
For example, when I switch between 3-Nen D-Gumi Glass no Kamen and it's manga I can see the difference because one overflows and one doesn't.

**Review by swindiggie — APPROVED** [review]

**Comment by swindiggie** [comment]
I see what you are talking about

**Pull request merged**
